### ISSUE TITLE
Null check operator used on a null value -  showcaseview/src/layout_overlays.dart:69

### ISSUE THREAD

**Issue by divijchhabra** [SimformSolutionsPvtLtd/flutter_showcaseview#397] opened 2023-09-21 10:56 UTC
Discovered a new bug through firebase crashlytics

io.flutter.plugins.firebase.crashlytics.FlutterError - Null check operator used on a null value. Error thrown widgets library.

Line No: 69 in src/layout_overlays.dart:

Code:
```
final topLeft =
                box.size.topLeft(box.localToGlobal(const Offset(0.0, 0.0)));

```

<img width="698" alt="Screenshot 2023-09-21 at 4 28 14 PM" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/55991906/4b572a17-6d59-4170-a9b7-dff3ef3fd82e">

**Comment by simform-chetan** [comment] 2023-09-22 15:50
Hi @divijchhabra Thanks for reporting the issue. Could you please provide more information on the stack trace or steps to produce it so we can have a closer look at it.

**Comment by nikiforosper** [comment] 2023-10-10 06:39
Hi i faced the same issue. 
Here is the formatted Stack trace on my Firebase Crashlytics:
<img width="1212" alt="Screenshot 2023-10-10 at 9 37 11 AM" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/56020828/7d7e1971-0f4c-4c8a-a427-f09f3c16284a">

Full stack trace file:
[showcaseview_stack_trace.txt](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/files/12853599/showcaseview_stack_trace.txt)

**Comment by divijchhabra** [comment] 2023-10-20 06:24
@nikiforosper were you able to find out the issue? Or else I'm thinking of adding some null checks whenever it builds the overlay widget

**Comment by nikiforosper** [comment] 2023-10-20 13:32
@divijchhabra I couldn't reproduce the issue. But I noticed that most of the reports were in landscape orientation.

**Comment by adar2378** [comment] 2023-10-23 09:13
Same issue 

![image](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/8059258/8e93006c-55d6-4446-9e8f-719d922ee167)

**Comment by adar2378** [comment] 2023-10-23 09:23
Could be related to 
https://github.com/flutter/flutter/issues/121385

**Comment by n3rdkid** [comment] 2023-11-22 11:42
Any update on this?

Similar issue is being reported by Sentry, yet we are unable to re-create it. 

@divijchhabra did you find any solution for it?

**Comment by aditya-css** [comment] 2024-04-29 05:10
Have released 2.1.0 version with potential fix for this. Closing this issue considering that. Please feel free to reopen if faced again.

**Closed by aditya-css** 2024-04-29 05:10 UTC

**Comment by wiesnery** [comment] 2025-01-04 10:22
This issue has come up once again in 3.0.0.

Please find the related Stack Traces here:

`Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown .
       at RenderObject.getTransformTo(object.dart:3405)
       at RenderBox.localToGlobal(box.dart:2899)
       at AnchoredOverlay.build.<fn>.<fn>(layout_overlays.dart:71)
       at _OverlayEntryWidgetState.build(overlay.dart:411)
...
`

and

`Bad state: RenderBox was not laid out: RenderTransform#5b017. Error thrown .
       at RenderBox.size(box.dart:2212)
       at RenderTransform._effectiveTransform(proxy_box.dart:2527)
       at RenderTransform.applyPaintTransform(proxy_box.dart:2609)
       at RenderObject.getTransformTo(object.dart:3430)
       at RenderBox.localToGlobal(box.dart:2899)
...`

However I have not been able to reproduce it in an Emulator
The issue is occurring on Pixel 7 Pro with Android 15 and Galaxy A3 with Android 8

Would be good to get support on how to track this down

**Comment by Sahil-Simform** [comment] 2025-01-07 06:04
Hi @wiesnery, We have updated the logic to fix this issue, and it will be available in the next release. For now, you can use the master branch, which contains the fix for this issue.

**Comment by wiesnery** [comment] 2025-01-07 07:19
Hi @Sahil-Simform,

Thank you for the quick reply and thanks for looking into it.
I cannot see a PR attached to this issue nor can I see any commits within the last week on the master.

Am I missing something or what fix are you referring to?

Cheers

**Comment by Sahil-Simform** [comment] 2025-01-07 08:13
Hi @wiesnery, PR #487 provides the fix for this issue.

**Comment by wiesnery** [comment] 2025-01-07 08:30
Thank you for the reference!
For when are you planning the release?

**Comment by Sahil-Simform** [comment] 2025-01-07 08:32
Very soon

**Comment by Sahil-Simform** [comment] 2025-01-07 08:34
Very soon, 
Thanks

**Comment by Sahil-Simform** [comment] 2025-01-07 11:01
Hi @wiesnery,

We’ve released a new version of the package! 🎉 You can check it out now.

If you find the package helpful, we’d appreciate it if you could give it a star on GitHub and a like on Pub. 😊

Thank you for your support!

**Comment by wiesnery** [comment] 2025-01-07 11:23
Thanks for the quick release and note.

Unfortunately another error appeared after upgrading to 4.0.0 but at the same place

```
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#2ee93](state: _OverlayEntryWidgetState#89c90):
RenderBox was not laid out: RenderFractionalTranslation#e3008 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2176 pos 12: 'hasSize'

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///<omitted>
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2176:12)
#3      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2961:24)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3430:25)
#5      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2899:39)
#6      AnchoredOverlay.build.<anonymous closure>.<anonymous closure> (package:showcaseview/src/layout_overlays.dart:72:23)
#7      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:411:36)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5743:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5631:15)
```

and shortly after

```
The following assertion was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#45b64](state: _OverlayEntryWidgetState#593f8):
RenderBox was not laid out: RenderFractionalTranslation#e3008 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 2176 pos 12: 'hasSize'

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///<omitted>
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:2176:12)
#3      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2961:24)
#4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:3430:25)
#5      RenderBox.localToGlobal (package:flutter/src/rendering/box.dart:2899:39)
#6      AnchoredOverlay.build.<anonymous closure>.<anonymous closure> (package:showcaseview/src/layout_overlays.dart:72:23)
#7      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:411:36)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5743:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5631:15)
``

**Comment by Sahil-Simform** [comment] 2025-01-07 12:14
Thanks for checking this issue in the latest release.
Can you please provide a minimal reproducible code for this? So we can check what is wrong.

**Comment by wiesnery** [comment] 2025-01-07 18:02
I have found the root cause for this:
I have used two Pages A and B
I went from A -to-> B with push()
Then I wanted to return to the old page  B -back-to-> A with a pushNamedAndRemoveUntil()

I wanted to do it this way cause I have init logic in my view A which I wanted to re-trigger (e.g. the tutorial should start if not yet started or reset)
The problem I think is that this causes A first to be placed on top of B (so A|B|A) before removing A and B underneath.
Normally this is not a problem but as you are using a final static GlobalKey to be able to access it from anywhere, the key is being used (at least) twice and this is what causes flutter to crash.

I have resolved it by doing A -to-> B with pop() instead but now I am listening in A for the push() Future to complete to re-trigger my init logic.
Somewhat unfulfilling but ok for the moment.

My conclusions from this:

- I should switch to something like a navigation delegate on A to do my init logic
- However it would be good if the showcaseview library could be a bit more resilient to the pushNamedAndRemoveUntil() method used. Maybe by replacing the final static GlobalKey with a GlobalKey which gets reassigned with a rebuild or so.
