### ISSUE TITLE
This widget has been unmounted, so the State no longer has a context

### ISSUE THREAD

**Issue by kirill-21** [SimformSolutionsPvtLtd/flutter_showcaseview#313] opened 2022-12-08 17:16 UTC
[DartError] This widget has been unmounted, so the State no longer has a context (and should be considered defunct).Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.; 
#0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:935:9)
#1      State.context (package:flutter/src/widgets/framework.dart:941:6)
#2      _OverlayBuilderState.addToOverlay (package:showcaseview/src/layout_overlays.dart:172:47)
#3      _OverlayBuilderState.showOverlay (package:showcaseview/src/layout_overlays.dart:164:7)
#4      _OverlayBuilderState.syncWidgetAndOverlay (package:showcaseview/src/layout_overlays.dart:195:7)
#5      _OverlayBuilderState.reassemble.<anonymous closure> (package:showcaseview/src/layout_overlays.dart:144:39)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#8      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
#9      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Happens when you try switching between screens very fast and ShowCaseWidget.of(context).startShowCase doesn't have time to start showing the showcase

**Comment by kirill-21** [comment] 2022-12-08 17:32
![image](https://user-images.githubusercontent.com/63228361/206522943-b1f64021-839b-4b52-abc8-4faab80063c8.png)
And one more similar error

**Comment by errajibadr** [comment] 2022-12-28 10:04
Hello,

i'm having the same issue, when hot reloading a page with  a showcase widget. not even calling the postframecallback yet.

This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

is there any work-around?

thank you.

**Comment by kirill-21** [comment] 2022-12-28 10:18
> 

```dart
  showcaseview:
    git:
      url: https://github.com/kirill-21/flutter_showcaseview
      ref: master
```
Just use this version of package until fix is merged into this repo

**Comment by faiyaz-shaikh** [comment] 2023-02-22 12:05
Hi @kirill-21, Thanks for pointing out the issue. Can you please share the reproducible code as I am not able to reproduce it?

**Comment by kirill-21** [comment] 2023-02-22 12:23
> pointing out the issue. Can you please share the reproducible

You can just approve this https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/pull/333 pull request, i already fixed this problem there

**Comment by faiyaz-shaikh** [comment] 2023-02-22 12:32
@kirill-21 Unfortunately, we can not merge PR until we can reproduce it. Please share the reproducible code so we can check the root cause.

**Comment by kirill-21** [comment] 2023-03-16 06:17
> @kirill-21 Could you please use the latest version of showcaseview? I guess it will fix your concern. Thank you!!

My issue can only be fixed after this changes: https://github.com/kirill-21/flutter_showcaseview/commit/152c484318f29b3ea890b65af6fa6157fe857c19

**Comment by dhvanit-v-simformsolutions** [comment] 2023-03-16 06:21
> > @kirill-21 Could you please use the latest version of showcaseview? I guess it will fix your concern. Thank you!!
> 
> My issue can only be fixed after this changes: [kirill-21@152c484](https://github.com/kirill-21/flutter_showcaseview/commit/152c484318f29b3ea890b65af6fa6157fe857c19), official branch works with errors

Okay, so could you please share the code snippet which produces these errors? It would be helpful for us to find the root cause.

**Comment by kirill-21** [comment] 2023-03-16 07:06
> > > @kirill-21 Could you please use the latest version of showcaseview? I guess it will fix your concern. Thank you!!
> > 
> > 
> > My issue can only be fixed after this changes: [kirill-21@152c484](https://github.com/kirill-21/flutter_showcaseview/commit/152c484318f29b3ea890b65af6fa6157fe857c19), official branch works with errors
> 
> Okay, so could you please share the code snippet which produces these errors? It would be helpful for us to find the root cause.

No, this issue is being automatically reported to apps server as an unhandled exception, many users face this error, but I have no idea how to reproduce it, so I fixed it on my own branch and am using it right now to avoid errors, fix is simple and does not do anything bad, you can implement it within a minute

**Comment by ujas-m-simformsolutions** [comment] 2023-07-14 05:52
I think the error suggest that somehow Showcase is trying to show tooltip and at same time that screen is closed so `context` for that screen is no longer available.

**Comment by ramanraja** [comment] 2023-12-30 09:10
At least a check like `if (!context.mounted) `  is expected to work. But it seems this very line raises the exception. 
Even a lower level check like `if (context == null)` raises the  same exception  "This widget has been unmounted, so the State no longer has a context".

**Comment by ramanraja** [comment] 2023-12-31 06:06
> @kirill-21 Unfortunately, we can not merge PR until we can reproduce it. Please share the reproducible code so we can check the root cause.

Are we still waiting to reproduce this bug - or have you found a way to reproduce it ? I have a piece of code that may bring up the error.

**Comment by ramanraja** [comment] 2023-12-31 06:26
This invalid-context bug can be reproduced by introducing a deliberate flaw in our workflow:

We have a button handler that calls an async method; but it pops the context without waiting for the method to return:
```

  onPressed: () {
    uploadToCloud(); 
    Navigator.pop(context);  // this is a bug: it prematurely pops the current page
  }
  
  Future<void> uploadToCloud() async{
    await someLongRunningAPICall ();
    // the following line crashes the app:
    if (context == null) return;
    // if the above line was commented out,the following check crashes the app:
    if (!context.mounted) return;
    Navigator.pop(context);
  }
  
```
  Note 1: If the context is invalid, we are not able to perform the check `if (!context.mounted)`
  Note 2: We cannot even null-check the context. The mere mention of context on the left side of an expression raises an exception.
  Note 3: In both the above cases, the exception thrown is  `"This widget has been unmounted, so the State no longer has a context"`.

**Comment by aditya-css** [comment] 2024-03-07 06:35
Hey @kirill-21, due to not being able to reproduce this issue, I am closing it along with your PR for the same. If you face this issue again then please feel free to re open along with reproducible code.

**Closed by aditya-css** 2024-03-07 06:35 UTC

**Comment by kirill-21** [comment] 2024-03-07 06:37
Lol, i LITERALLY made pull request with a fix for that.... 2 times... Why can't you just merge it? I showed you the place and fixed it

> Hey @kirill-21, due to not being able to reproduce this issue, I am closing it along with your PR for the same. If you face this issue again then please feel free to re open along with reproducible code.

**Comment by aditya-css** [comment] 2024-03-07 06:47
We totally appreciate your contribution, but we have to know the underlying issue and how to reproduce it before merging a fix for it. If you can provide a reproducible code then we would be happy to check and accept your contribution.

**Comment by kirill-21** [comment] 2024-03-07 06:48
> We totally appreciate your contribution, but we have to know the underlying issue and how to reproduce it before merging a fix for it. If you can provide a reproducible code then we would be happy to check and accept your contribution.

I guess you just never used this package before because issue is reproducible within a few seconds after just testing this inside a real project

**Comment by ramanraja** [comment] 2024-03-08 11:12
Could you try my suggestion above please?
1.    Pop the current widget: Navigator.pop(context);   
 2.   Call any async method
 3.   Test if the context is still mounted (which of course, will not be)
 We would expect it to return false, but the app crashes.
