### ISSUE TITLE
Error: The getter 'headline6', 'subtitle2', isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by lighbit** [SimformSolutionsPvtLtd/flutter_showcaseview#447] opened 2024-05-25 10:12 UTC
**Describe the bug**
The error occurs when launching the Flutter app. The headline6 and subtitle2 getters are not defined for the class TextTheme in the showcaseview package.

**To Reproduce**
1. Go to 'launch the Flutter app'
2. Click on 'run the app in debug mode'
3. Scroll down to  'observe the console output'

**Expected behavior**
The app should compile and run without errors.

**Screenshots**

**Smartphone (please complete the following information):**
- OS: [e.g. Android]
 - Version [e.g. 33]

**Additional context**

Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
/C:/Users/<user>/AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/TOOL/FLUTTER/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
            .headline6!
             ^^^^^^^^^
/C:/Users/<user>/AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:163:14: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/TOOL/FLUTTER/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
            .subtitle2!
             ^^^^^^^^^
/C:/Users/<user>/AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:463:50: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/TOOL/FLUTTER/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                                .headline6!
                                                 ^^^^^^^^^
/C:/Users/<user>/AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:484:48: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/TOOL/FLUTTER/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
                                              .subtitle2!
                                               ^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\TOOL\FLUTTER\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

**Comment by aditya-css** [comment] 2024-05-25 10:13
Duplicate of #434

**Closed by aditya-css** 2024-05-25 10:13 UTC
