### ISSUE TITLE
[Flutter Web] The widgets for which the hint is displayed are not highlighted

### ISSUE THREAD

**Issue by HornyPony** [SimformSolutionsPvtLtd/flutter_showcaseview#390] opened 2023-08-26 11:33 UTC
**Describe the bug**
In the web version, the widget for which the hint is displayed is not highlighted. The release was made through the "flutter build web" command. 
Works fine in Android and iOS, version on package: 2.0.3

**To Reproduce**
1. flutter build web
2. Open app in browser
3. See error

**Expected behavior**
The widget highlighted in red in the screenshot is highlighted

**Desktop (please complete the following information):**
 - Browser [chrome]

<img width="457" alt="image" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/67595447/97bcb8df-2508-4970-babc-c88ae11a1f1b">

**Comment by HornyPony** [comment] 2023-08-26 11:37
I noticed that in the "Inspect Element" mode, the widget is highlighted

<img width="1303" alt="image" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/67595447/fd904e6a-8d27-4af0-91cd-267dfa3cb19d">

**Comment by jaiminrana05** [comment] 2023-08-29 09:42
Hi @HornyPony, can you please provide more information about the issue you're facing? Additionally, kindly share the code snippets as I'm unable to reproduce the problem.

**Comment by HornyPony** [comment] 2023-08-29 10:09
> Hi @HornyPony, can you please provide more information about the issue you're facing? Additionally, kindly share the code snippets as I'm unable to reproduce the problem.

There is nothing special in the code - everything is according to the instructions from pub.dev. Hints are shown in the mobile version of the app, but do not work in the web version. But sometimes they are shown, but it happens that the wrong area is highlighted. Maybe I need to add something to the "flutter build web" command?

**Comment by HornyPony** [comment] 2023-08-30 15:58
> Hi @HornyPony, can you please provide more information about the issue you're facing? Additionally, kindly share the code snippets as I'm unable to reproduce the problem.

I found a reason but i still need ur help. It turned out that the problem is as follows: the hint is highlighted, but it is incorrectly positioned, because in the web version the application does not occupy the entire screen, but a certain part of it. However, the hint is highlighted based on the size of the user's entire screen. 
The arrow highlights the shifted hint, the red rectangle - where it should be, and the green one - the area of displacement relative to the entire screen

<img width="1680" alt="image" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/67595447/9201dbeb-d478-4ec7-aeeb-17fae0095196">

**Comment by HornyPony** [comment] 2023-08-30 16:07
The problem is most clearly seen here

<img width="1680" alt="image" src="https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/assets/67595447/63d8f5f4-de8d-4865-b6fa-69501067d783">

**Comment by HornyPony** [comment] 2023-08-31 16:29
@jaiminrana05 The same problem is here: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/383

Can I get any information please?

**Comment by jaiminrana05** [comment] 2023-09-01 04:48
Thank you @HornyPony, for sharing the code snippets. It's really helpful for us to have them as we work on resolving this issue.

**Comment by aditya-css** [comment] 2024-02-07 12:39
Thank you @HornyPony for providing all the details and your cooperation. This issue looks like duplicate of #383 and a PR (#394 ) is currently open that would potentially fix this.

**Closed by aditya-css** 2024-02-07 12:39 UTC
Labels: duplicate
