### ISSUE TITLE
add left & right to TooltipPosition

### ISSUE THREAD

**Issue by SPSpisoft** [SimformSolutionsPvtLtd/flutter_showcaseview#399] opened 2023-10-21 11:45 UTC
Please add the option to specify left and right to TooltipPosition.
We have a widget that covers the entire height, and cannot use the top or bottom option to display the Tooltip.

**Comment by SaiZayarHtet7** [comment] 2023-11-08 08:45
Yes We need it for the widget with the height of device, because the  tooltips disappear outside

**Comment by aditya-css** [comment] 2024-03-07 18:01
Closing this issue as it is duplicate of #54.

**Closed by aditya-css** 2024-03-07 18:01 UTC
Labels: duplicate, enhancement
