### ISSUE TITLE
Option for blocking dismissal of ShowCaseView

### ISSUE THREAD

**Issue by 7AveNooN7** [SimformSolutionsPvtLtd/flutter_showcaseview#240] opened 2022-07-05 19:15 UTC
I can't find such a functionality in the current version. For now, user can dismiss the showcasewidget by clicking on the barrier.

Would be great if u can introduce possibility to not let user bypass a tooltip, instead let the developer decide when and how it can be dismissed.

**Comment by vatsaltanna** [comment] 2022-08-01 12:52
Duplicate of #237

**Closed** 2022-08-01 12:54 UTC
