### ISSUE TITLE
showcaseview after upgrade to flutter 3.7.1 not disable target click

### ISSUE THREAD

**Issue by AlmutawakelSukaina** [SimformSolutionsPvtLtd/flutter_showcaseview#348] opened 2023-03-02 13:40 UTC
**You can press target widget even if you set disableDefaultTargetGestures: true**  

,Which navigate to next page before complete showcases.
This problem happened after upgrade to flutter 3.7.1.

To reproduce the issue:
1. Create An app with showcaseview (target widget navigate to new page)
2. When showcase start then click on target widget 
3. App navigate to new widget before complete showcase

**Expected behavior**
Before upgrade to flutter 3.7.1 target widget is disabled until showcaseview complete>

**Screenshots**

[As shown in the pictures The Floating action button (+) is the target widget](https://i.stack.imgur.com/Z4Fzl.png)

[This happened after click the target](https://i.stack.imgur.com/mmI04.png)

**This is full code**

//main page

     import 'package:flutter/material.dart';
     import 'package:showcaseview/showcaseview.dart';

      void main() {
      runApp(const MyApp());
      }

 //MyApp Page

      class MyApp extends StatelessWidget {
      const MyApp({super.key});

      @override
      Widget build(BuildContext context) {
      return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
      primarySwatch: Colors.blue,
      ),
        //showCaseWidget
          home: ShowCaseWidget(
          disableMovingAnimation: true,
         disableScaleAnimation: true,
         builder: Builder(
          builder: (_) =>
              const MyHomePage(title: 'Flutter Demo Home Page')),
          onFinish: () async {}),
         );
         }
       }
//MyHomePage

       class MyHomePage extends StatefulWidget {
        const MyHomePage({super.key, required this.title});

         final String title;
 
         @override
        State<MyHomePage> createState() => _MyHomePageState();
         }

     class _MyHomePageState extends State<MyHomePage> {
      final int _counter = 0;
      //showCase keys
      final _increment = GlobalKey();
      final _decrement = GlobalKey();
      final _texxt = GlobalKey();

      void navigateToPage(fun) {
       Navigator.push(
        context,
        MaterialPageRoute(
        builder: (_) => ShowCaseWidget(
            builder: Builder(builder: (_) => fun), onFinish: () async 
               {})));
            }

        void _incrementCounter() {
         navigateToPage(const Increment());
            }

        void _textWidget() {
          navigateToPage(const TextWidget());
          }

        void _decrementCounter() async {
        navigateToPage( const Decrement());
          }

       @override
        void initState() {
       // TODO: implement initState
         super.initState(); 
       //start showcase
       WidgetsBinding.instance.addPostFrameCallback(
       (_) => ShowCaseWidget.of(context)
        .startShowCase([_increment, _decrement, _texxt]),
           );
           }

         @override
       Widget build(BuildContext context) {
       return Scaffold(
        appBar: AppBar(
       title: Text(widget.title),
       ),
       body: InkWell(
       onTap: _textWidget,
        child: Center(
        child: CustomShowcaseWidget(
        description: 'this is text widget ',
        globalKey: _texxt,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(   
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
          ),
         ),
        ),
         ),
         floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
         CustomShowcaseWidget(
            description: 'this is increment floating button widget ',
          globalKey: _increment,
           child: FloatingActionButton(
            heroTag: "increment",
            onPressed: _incrementCounter,
            tooltip: 'Increment',
          child: const Icon(Icons.add),
          ),
         ),
         CustomShowcaseWidget(
          description: 'this is decrement floating button widget ',
          globalKey: _decrement,
          child: FloatingActionButton(
          heroTag: "decrement",
          onPressed: _decrementCounter,
          tooltip: 'decrement',
          child: const Icon(Icons.minimize),
           ),
          ),
        ],
        ), 
         );
        }
        }

//CustomShowcaseWidget

          class CustomShowcaseWidget extends StatelessWidget {
          final Widget child;
          final String description;
          final GlobalKey globalKey;

          const CustomShowcaseWidget(
          {required this.description,
          required this.child,
          required this.globalKey,
          Key? key})
         : super(key: key);

         @override
          Widget build(BuildContext context) => Showcase(
         key: globalKey,
          tooltipBackgroundColor: Colors.green,
          tooltipPadding:
          const EdgeInsets.symmetric(horizontal: 10, vertical: 10),
          showArrow: true,
         disableMovingAnimation: true,
         disableScaleAnimation: true,
         disableDefaultTargetGestures: true,
        description: description,
        descTextStyle: const TextStyle(
        color: Colors.white, fontWeight: FontWeight.bold, fontSize: 
          20),
             child: child,
           );
             }
// Increment Widget

          class Increment extends StatelessWidget {
         const Increment({super.key});

       @override
      Widget build(BuildContext context) {
        return Container(
          color: Colors.white,
          child: const Center(
            child: Text("Increment Screen"),
           ),
            );
         }
      }
//Decrement Widget

       class Decrement extends StatelessWidget {
        const Decrement({super.key});

        @override
       Widget build(BuildContext context) {
     return Container(
        color: Colors.white,
         child: const Center(
          child: Text("Decrement Screen"),
          ),
        );
         }
        }
//TextWidget

           class TextWidget extends StatelessWidget {
          const TextWidget({super.key});

         @override
          Widget build(BuildContext context) {
          return Container(
          color: Colors.white,
           child: const Center(
          child: Text("Text Screen"),
          ),
             );
        }
         }

**Comment by agelogeo** [comment] 2023-03-03 09:44
Same for me, It makes the package unusable. User navigates on the next page and everything is broken then.

**Comment by luis901101** [comment] 2023-03-04 01:10
I'm facing the same issue... currently working on a workaround solution in the mean time, by defining a visibility flag which will be changed onStart/onComplete then used to know if target click must be ignored...

**Comment by luis901101** [comment] 2023-03-04 01:12
This seems duplicated of: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues/346

**Comment by vatsaltanna** [comment] 2023-03-06 20:48
Can you please share flutter version in which this was working as per your expectation?

**Comment by vatsaltanna** [comment] 2023-03-06 20:53
FYI, `disableDefaultTargetGestures` only ignores the default gestures assigned inside the package and not the external gesture added on the target widget.

**Comment by vatsaltanna** [comment] 2023-03-06 21:30
Solution:

remove :

`disableDefaultTargetGestures: true,`

add:

```
disposeOnTap: false,
onTargetClick: () {},
```

**Comment by vatsaltanna** [comment] 2023-03-06 21:38
FYI: `disableDefaultTargetGestures: true` is provided to override the default gesture provided by showcase widget so that developer can use their own gestures in target widget.

**Comment by vatsaltanna** [comment] 2023-03-07 07:06
Duplicate of #346

**Closed by vatsaltanna** 2023-03-07 07:06 UTC

**Comment by AlmutawakelSukaina** [comment] 2023-03-11 07:36
@vatsaltanna Issue not solved in the leatest version showcaseview: ^2.0.2. 
I'm still able to click target widget even if the property disableDefaultTargetGestures set to true.
My Flutter version is updated to 3.7.6

**Comment by vatsaltanna** [comment] 2023-03-11 08:42
Hi @AlmutawakelSukaina,  please remove `disableDefaultTargetGestures: true` as the use case of it is to pass gesture to target widget and you will get callback in your external gestures of target widget if you want to ignore that gestures then use below code after removeing `disableDefaultTargetGestures` or set it to `false` .


> Solution: remove and add below code respectively in `Showcase` widget.
> 
> remove :
> 
> `disableDefaultTargetGestures: true,`
> 
> add:
> 
> ```
> disposeOnTap: false,
> onTargetClick: () {},
> ```
