### ISSUE TITLE
error with flutter 3.22.0

### ISSUE THREAD

**Issue by fazelit** [SimformSolutionsPvtLtd/flutter_showcaseview#439] opened 2024-05-16 07:04 UTC
/C:/Users/foula/AppData/Local/Pub/Cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/D:/MyApplications/runtime/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
            .headline6!

**Comment by rokk4** [comment] 2024-05-16 07:37
Same issue here on 3.22.0
```
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../fvm/versions/3.22.0/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
            .headline6!
             ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:163:14: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../fvm/versions/3.22.0/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
            .subtitle2!
             ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:463:50: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../fvm/versions/3.22.0/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
                                                .headline6!
                                                 ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:484:48: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../../fvm/versions/3.22.0/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
                                              .subtitle2!
                                               ^^^^^^^^^
Target kernel_snapshot failed: Exception
```

**Comment by aditya-css** [comment] 2024-05-16 08:07
Duplicate of #434

**Closed by aditya-css** 2024-05-16 08:07 UTC
