### ISSUE TITLE
Error when I use Showcase.withWidget(...) in animated tabs

### ISSUE THREAD

**Issue by macortesn** [SimformSolutionsPvtLtd/flutter_showcaseview#130] opened 2021-08-20 16:50 UTC
**Describe the bug**

I'm using bottom tabs for each section of my application. I'm trying to start show case when i change to specifcic tab as the documentation says:

```
void initState() {
    super.initState();
    //Start showcase view after current widget frames are drawn.
    WidgetsBinding.instance!.addPostFrameCallback((_) =>
        ShowCaseWidget.of(context)!
            .startShowCase([_one, _two, _three, _four, _five]));
}
```
And the Showcase widget is showed , but i have the next error.

```
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
setState() or markNeedsBuild() called during build.

This SlideTransition widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: SlideTransition
    animation: AnimationController#ce5c7(⏮ 0.000; paused)➩Cubic(0.42, 0.00, 0.58, 1.00)➩Tween<Offset>(Offset(0.0, 0.0) → Offset(0.0, 0.1))➩Offset(0.0, 0.0)
    state: _AnimatedState#23975
The widget which was currently being built when the offending call was made was: Showcase-[GlobalKey#f0747]
    dependencies: [MediaQuery, _EffectiveTickerMode, _InheritedShowCaseView]
    state: _ShowcaseState#0b6b2(tickers: tracking 1 ticker)
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure>
package:flutter/…/widgets/framework.dart:4217
#1      Element.markNeedsBuild
package:flutter/…/widgets/framework.dart:4232
#2      State.setState
package:flutter/…/widgets/framework.dart:1108
#3      _AnimatedState._handleChange
package:flutter/…/widgets/transitions.dart:168
#4      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:136
```
Does anyone know how I can solve this?

**Smartphone (please complete the following information):**
 - Device: Xiaomi redmi note 10 lite
 - OS: Android 10

**Additional context**

This is my widget to create the bottom tabs: 
```
import 'dart:math' as math;

import 'package:flutter/material.dart';

enum TransitionType { circular, slide, fade }

class BottomBarPageTransition extends StatefulWidget {
  final IndexedWidgetBuilder builder;
  final int currentIndex;
  final int totalLength;
  final TransitionType transitionType;
  final Duration transitionDuration;
  final Curve transitionCurve;

  const BottomBarPageTransition(
      {required this.builder,
      required this.currentIndex,
      required this.totalLength,
      this.transitionType = TransitionType.circular,
      this.transitionCurve = Curves.easeIn,
      this.transitionDuration = const Duration(milliseconds: 300)});

  @override
  _BottomBarPageTransitionState createState() =>
      _BottomBarPageTransitionState();
}

class _BottomBarPageTransitionState extends State<BottomBarPageTransition>
    with TickerProviderStateMixin {
  int? _displayingIndex;
  int? _animatingIndex;
  int? _tempAnimatingIndex;
  int? _index;
  late AnimationController _animationController;

  @override
  void initState() {
    super.initState();
    _animationController =
        AnimationController(vsync: this, duration: widget.transitionDuration);

    _animationController.addListener(() {
      if (_animationController.status == AnimationStatus.forward) {
        _tempAnimatingIndex = _animatingIndex;
      } else if (_animationController.status == AnimationStatus.dismissed) {
        if (_tempAnimatingIndex != null) _displayingIndex = _tempAnimatingIndex;
      }

      if (_animationController.status == AnimationStatus.completed) {
        _displayingIndex = _animatingIndex;
        _animatingIndex = null;
        _animationController.stop();
        _tempAnimatingIndex = null;
      }

      setState(() {});
    });
    _index = widget.currentIndex;
  }

  @override
  void dispose() {
    _animationController.dispose();
    super.dispose();
  }
  
  @override
  Widget build(BuildContext context) {
    _displayingIndex ??= _index;
    if (_index != widget.currentIndex) {
      _index = widget.currentIndex;
      WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
        _animatingIndex = widget.currentIndex;
        _animationController.duration = widget.transitionDuration;
        _animationController.reset();
        _animationController.forward();
      });
    }

    final bool canAnimate =
        _animatingIndex != null && _displayingIndex != _animatingIndex;

    return Stack(
      
      children: <Widget>[
        widget.builder(context, _displayingIndex!),
        if (canAnimate && widget.transitionType == TransitionType.circular)
          ClipOval(
            clipper: _OvalClipper(
                widget.currentIndex,
                widget.totalLength,
                Tween(begin: 0.0, end: 1.0)
                    .chain(CurveTween(curve: widget.transitionCurve))
                    .animate(_animationController)
                    .value),
            child: widget.builder(context, _animatingIndex!),
          ),
        if (canAnimate && widget.transitionType == TransitionType.slide)
          SlideTransition(
            position: Tween<Offset>(
                    begin: Offset(
                        _animatingIndex! < _displayingIndex! ? -1 : 1, 0),
                    end: Offset.zero)
                .chain(CurveTween(curve: widget.transitionCurve))
                .animate(_animationController),
            child: widget.builder(context, _animatingIndex!),
          ),
        if (canAnimate && widget.transitionType == TransitionType.fade)
          FadeTransition(
            opacity: Tween<double>(begin: 0.0, end: 1.0)
                .chain(CurveTween(curve: widget.transitionCurve))
                .animate(_animationController),
            child: widget.builder(context, _animatingIndex!),
          )
      ],
    );
  }
}

class _OvalClipper extends CustomClipper<Rect> {
  int currentIndex;
  int length;
  double value;

  _OvalClipper(this.currentIndex, this.length, this.value);

  @override
  Rect getClip(Size size) {
    final double step = currentIndex + size.width / length;
    final double halfStep = step / 2;
    final double d = math.sqrt(
            (size.width + halfStep) + (size.height + 30) * (size.height + 30)) *
        2.5 *
        value;
    return Rect.fromCenter(
        center: Offset((currentIndex * step) + halfStep, size.height + 30),
        width: d,
        height: d);
  }

  @override
  bool shouldReclip(CustomClipper<Rect> oldClipper) {
    if (oldClipper is _OvalClipper) {
      return oldClipper.value != value ||
          oldClipper.currentIndex != currentIndex;
    }
    return true;
  }
}

```

And i use it in an screen , where `getBody()` is the content of the tab. This content is wrapped by `ShowCaseWidget(builder: Builder(builder: (context) {....}`

```
.......
@override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BottomBarPageTransition(
        builder: (_, index) => _getBody(index),
        currentIndex: _currentPage,
        totalLength: totalPage,
        transitionType: transitionType,
        transitionDuration: duration,
        transitionCurve: curve,
      ),
      bottomNavigationBar: SafeArea(
        child: AnimatedBottomBar((selectedIndex) {
          setState(() {
            _currentPage = selectedIndex as int;
          });
        }),
      ),
    );
  }
.......
```

**Comment by ujas-m-simformsolutions** [comment] 2021-09-13 10:40
@macortesn I tried reproducing bug using your code but it was working fine for me. can you share more details to reproduce it?

**Comment by vatsaltanna** [comment] 2022-02-14 07:04
I am closing this issue for now due to the lack of information. Feel free to reopen this if you face this issue again.

**Closed by vatsaltanna** 2022-02-14 07:04 UTC
