### ISSUE TITLE
`Showcase.withWidget` constructor hasn`t onToolTipClick field

### ISSUE THREAD

**Issue by reacct** [SimformSolutionsPvtLtd/flutter_showcaseview#349] opened 2023-03-03 08:06 UTC
**Describe the bug**
`Showcase.withWidget` constructor hasn`t onToolTipClick field. Customized tooltip is always tappable.

**To Reproduce**
1. Create showcase with the Showcase.withWidget constructor.

**Expected behavior**
`Showcase.withWidget` constructor has onToolTipClick field. Or tooltip created with `Showcase.withWidget` constructor should be untappable.

**Comment by vatsaltanna** [comment] 2023-03-06 20:59
Hi @reacct , This issue looks little unclear, can you please share more details? Are you asking for tap gesture of `Showcase.withWidget` or something else?

**Comment by reacct** [comment] 2023-03-07 06:13
Hi @vatsaltanna , I mean if I want to use tap on tooltip (i.e. wrap `container` in GestureDetector) then `disposeOnTap` will not make sense.

**Comment by vatsaltanna** [comment] 2023-03-10 10:35
yes, because you will have full control on your tooltip widget and I guess `disposeOnTap` will work for the target widget.

**Comment by ujas-m-simformsolutions** [comment] 2023-07-14 11:46
@reacct When you are providing your custom widget to Showcase.withWidget then you can just wrap your widget with GestureDetector and have onTap events on it and this is the intended behavior. I'm going to close this issue, feel free to create a new one if you have any issues

**Closed** 2023-07-14 11:47 UTC
Labels: invalid
