### ISSUE TITLE
[ANALYSIS ISSUE] app cant't be resolved

### ISSUE THREAD

**Issue by benjamin1571** [SimformSolutionsPvtLtd/flutter_showcaseview#444] opened 2024-05-19 09:46 UTC
**Describe the bug**
Using the  Flutter (Channel stable, 3.22.0) app can't be resolved

**To Reproduce**
1. Update to the latest version of flutter
2. Try running the app

../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
            .headline6!
             ^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:163:14: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.

**Comment by spiderion** [comment] 2024-05-19 09:56
the maintainer will need to run "dart fix --apply" to fix this issue.

**Comment by aditya-css** [comment] 2024-05-19 15:51
Duplicate of #434

**Closed by aditya-css** 2024-05-19 15:51 UTC
