### ISSUE TITLE
Show more than one widget in tutorial

### ISSUE THREAD

**Issue by mamodo123** [SimformSolutionsPvtLtd/flutter_showcaseview#143] opened 2021-09-16 21:53 UTC
Show more than one widget in the tutorial at same time. With or without the Ballon.
Ex:
![image](https://user-images.githubusercontent.com/47646223/133690721-7e7a0e7d-d75d-4eb8-812b-e5ea2968055b.png)

**Comment by vatsaltanna** [comment] 2021-09-17 06:33
Duplicate of #113

**Closed by vatsaltanna** 2021-09-17 06:33 UTC
