### ISSUE TITLE
Responsive showcase position 

### ISSUE THREAD

**Issue by BenCherif** [SimformSolutionsPvtLtd/flutter_showcaseview#222] opened 2022-06-01 14:10 UTC
Hi thanks for the awesome package ,the package was work perfectly ,but when i use this [responsive_framework](https://pub.dev/packages/responsive_framework) the showcase shown in wrong position , i've checked your code so i find the getposition function using mediaquery to get the width and height of the screen , is there a way to be able to customize the position so we can set our X & Y  for the get position function .
 Kind regards

**Comment by vatsaltanna** [comment] 2022-07-14 13:10
Hi @BirjuVachhani , What's your view on this issue ? I think responsive framework internally updates the mediaquery data and due to that packge recieves wrong height and width of the screen.

**Comment by BirjuVachhani** [comment] 2022-07-18 04:48
@vatsaltanna I am not sure tbh. @BenCherif Can you provide us some minimal reproducible code?

**Comment by BirjuVachhani** [comment] 2022-07-18 04:56
I just did a lookup and it seems that @vatsaltanna is right! It does provide different mediaQuery object.

**Comment by vatsaltanna** [comment] 2022-07-25 06:08
Hi @BenCherif , As reviewed by @BirjuVachhani and I this package is not compatible with responsive framework because it overrides the core logic of the package. So closing this for now feel free to reopen this for any other assistance required.

**Closed by vatsaltanna** 2022-07-25 06:08 UTC
