### ISSUE TITLE
Multiple tooltips for single showcase

### ISSUE THREAD

**Issue by hossam-96** [SimformSolutionsPvtLtd/flutter_showcaseview#363] opened 2023-03-21 10:00 UTC
**Is your feature request related to a problem? Please describe.**
I'm having a problem displaying a big amount of information in a single tooltip

**Describe the solution you'd like**
I would like to be able to pass a list of tooltips to a single showcase with each tooltip has it's own properties (description, position, ...)

**Describe alternatives you've considered**
I have tried to divide my showcase into smaller ones and to start all of them at the same time to display multiple tooltips but only the last call to the `startShowCase` function has been registered.

**Comment by ujas-m-simformsolutions** [comment] 2023-03-21 11:38
Duplicate of #113.

**Closed by ujas-m-simformsolutions** 2023-03-21 11:38 UTC
Labels: duplicate
