### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by MazenCoder** [SimformSolutionsPvtLtd/flutter_showcaseview#230] opened 2022-06-15 05:24 UTC
Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. 

When upgraded to flutter 3.0.0, there is a problem started to appear when running the app,
(The app works but there are error/s (warning/s) in the terminal).

**Comment by BirjuVachhani** [comment] 2022-06-15 08:13
@MazenCoder We are in process to release a fix for this.

**Comment by BirjuVachhani** [comment] 2022-06-15 08:14
Duplicate of #229

**Closed by BirjuVachhani** 2022-06-15 08:14 UTC
