### ISSUE TITLE
While using ShowCase widget, not scrolling to respective widget when its not visible.

### ISSUE THREAD

**Issue by sivaram16** [SimformSolutionsPvtLtd/flutter_showcaseview#62] opened 2020-08-13 05:58 UTC
Showcase(
                key: beatGlobalKey,
                description: StringResource.beatShowCaseDescp,
                showcaseBackgroundColor: ColorResource.BLUE15447a,
                titleTextStyle: TextStyle(
                    color: ColorResource.WHITE16dfff,
                    fontFamily: Font.ProximaNovaBold.value),
                descTextStyle: TextStyle(
                    color: ColorResource.WHITE16dfff,
                    fontFamily: Font.ProximaNovaRegular.value),
                shapeBorder: CircleBorder(),
                showArrow: true,
                spotlightPadding: EdgeInsets.all(10),
                child: PostActionButton(
                  !this.widget.post.isLike
                      ? ImageResource.unlikedIcon
                      : ImageResource.likedIcon,
                  'Beat',
                  tapFunction: _onTapLikePost,
                  titleColor: !this.widget.post.isLike
                      ? ColorResource.BLACK2f2f2f
                      : ColorResource.BLUE16dfff,
                ),
              ),

when i used the above code, showcase is not navigating to respective screen even in botttom, and overlay also not coming could anyone help with this? Thanks in adavance !

**Comment by BirjuVachhani** [comment] 2020-08-20 06:59
@ThalapathySiva It would be better if you could add some screenshots of the issue you're facing.

**Comment by leslie-tilton-bs** [comment] 2020-11-23 19:47
I'm also having this issue. I'm not sure why this issue is labeled as needing more information as it's very clear what the issue is. I do not have an example to provide at this moment but can create one if needed since the original poster is unresponsive.

I have a widget that is rendered in a scroll-able area and appears off screen below the bottom of the screen. While in portrait mode, it looks fine, if I turn the phone to landscape the showcase is no longer working as expected. A tool tip still pops up but there is no grey overlay.

Another possibly related issue is the showcase hovering over items that are partially covered by other widgets. In my case, the bottom navigation bar. 

I can see responsibility for proper highlighting should go to this library. If that is not possible, at least adding a way to run code in preparation for the next showcase should be exposed. There is an on complete function for the current index but no before starting step function which is extremely useful in preparing the UI for the next showcase.

**Comment by misuvija** [comment] 2020-11-23 22:40
Hi everyone!  
Just as @ThalapathySiva and @leslie-tilton-bs I'm experiencing the same issue. 

Please see my video with a quick example. Showcases 1, 2 and 3 are fine, but showcase 4's bubble doesn't gets complete displayed and showcase 5 for some reason makes the cool gray background disappear.

Hope you guys can take a look and fix!

BTW, cool widget, I love it :)
[RPReplay_Final1606170875.MP4.zip](https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/files/5586171/RPReplay_Final1606170875.MP4.zip)

**Comment by fransiskapw** [comment] 2021-03-23 08:06
I'm also experiencing the issue. The workaround for me was to scroll to the component then show the showcase

```
Future.delayed(const Duration(milliseconds: 200), () { // wait 2 second until component is loaded, then scroll 
  Scrollable.ensureVisible(_one.currentContext,duration: new Duration(milliseconds:500));
});
Future.delayed(const Duration(milliseconds: 650), () { 
  ShowCaseWidget.of(context).startShowCase([_one]);
});
```

Found weird behaviour though - the correctness of the showcase location depends on the value of the second delay (`Future.delayed(const Duration(milliseconds: 650)`) -> if I put 300, the background didn't show up. if i put 500, the background is a bit misplaced. for >= 650, the position is correct, so I put 650 as the value

**Comment by nwparker** [comment] 2021-10-21 06:19
> I also experienced the issue. The workaround for me was to scroll to the component then show the showcase
> 
> ```
> Future.delayed(const Duration(milliseconds: 200), () async { // wait 2 second until component is loaded, then scroll 
>   await Scrollable.ensureVisible(_one.currentContext,duration: new Duration(milliseconds:500));
>   ShowCaseWidget.of(context).startShowCase([_one]);
> });
> ```

Good idea, but don't use a timer.

Use `WidgetsBinding.instance.addPostFrameCallback((_) async {})`

**Comment by RobertHeim** [comment] 2022-02-24 22:56
I am not sure if the lib should handle scrolling. But it should make it possible to integrate scrolling.

The workaround of first scrolling to a position and then start the showcase does not wirk if you need to scroll between the steps.

# To scroll between steps try this:

``` 
ShowCaseWidget(
  onComplete: (index, key) {
    // scroll after completing step 1
    if (index == 1) {
      await Scrollable.ensureVisible(
        key.currentContext!,
        alignment: -1,
      );
    }
  },
  builder: Builder(builder: (_) => const MyPage()),
)
```
Note that you cannot use a `duration` of 'ensureVisible` because the showcase lib does not await the `onComplete` before drawing the tooltip. As a result if you would use a duration the tooltip would be drawn at a position that then is out of view after scrolling. This should be fixed in the lib. But I guess for most people it is fine without a duration for the moment.

**Comment by RobertHeim** [comment] 2022-02-25 02:49
After my last comment I decided to solve it and created the PR above. The active `Showcase` will be brought into (the center of the) view automatically. No setup / changes required.

![Peek 2022-02-25 03-39](https://user-images.githubusercontent.com/463840/155643584-b226be86-b392-453e-84db-c50d2d2b784e.gif)

If you want to use it before the merge/release you can change your pubspec.yml dependency:
```
  showcaseview: # ^1.1.4
    git:
      ref: '8892124'
      url: https://github.com/RobertHeim/flutter_showcaseview
```

**Comment by misuvija** [comment] 2022-02-25 16:52
This is awesome @RobertHeim, thanks a lot for adding support to the scrolling.

**Comment by mhilalsh** [comment] 2022-03-03 13:05
This is great @RobertHeim thanks so much! it's my first time to use a dependency like that before the merge.. is it safe to publish my app with it or should I wait till it's merged?

**Comment by RobertHeim** [comment] 2022-03-08 20:36
@mhilalsh 

> it's my first time to use a dependency like that before the merge.. is it safe to publish my app with it or should I wait till it's merged?

Well, if you trust the un-published code then it is safe. The merge makes it more trustful, because merged code is considered to being reviewed by the package author.

But keep in mind: You cannot update the lib until it will be merged. If the PR will not be merged then maintainability will be blocked. There will not be any merges of new features or fixes from main to this specific branch. However, you could do so on your own because everything relevant to this is open source.

**Closed** 2022-05-06 08:10 UTC
Labels: more information needed

**Comment by mahdinazmi** [comment] 2022-06-17 11:46
> After my last comment I decided to solve it and created the PR above. The active `Showcase` will be brought into (the center of the) view automatically. No setup / changes required.
> 
> ![Peek 2022-02-25 03-39](https://user-images.githubusercontent.com/463840/155643584-b226be86-b392-453e-84db-c50d2d2b784e.gif) [ ](https://user-images.githubusercontent.com/463840/155643584-b226be86-b392-453e-84db-c50d2d2b784e.gif) ![Peek 2022-02-25 03-39](https://user-images.githubusercontent.com/463840/155643584-b226be86-b392-453e-84db-c50d2d2b784e.gif) [ ](https://user-images.githubusercontent.com/463840/155643584-b226be86-b392-453e-84db-c50d2d2b784e.gif)
> 
> If you want to use it before the merge/release you can change your pubspec.yml dependency:
> 
> ```
>   showcaseview: # ^1.1.4
>     git:
>       ref: '8892124'
>       url: https://github.com/RobertHeim/flutter_showcaseview
> ```

How can i remove circular progress indiactor ?

**Comment by Zeinab-Kouhkan** [comment] 2024-06-24 09:15
```
void startShowCaseAsSoonAsBuildUI(BuildContext context) {
    if (!enableShowCase) {
      return;
    }
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Future.delayed(const Duration(milliseconds: 500), () async {
        ShowCaseWidget.of(context).startShowCase([services, menu, support]);
      });
    });
  }
```
