### ISSUE TITLE
Add position indication

### ISSUE THREAD

**Issue by Al-Krause-ex** [SimformSolutionsPvtLtd/flutter_showcaseview#354] opened 2023-03-12 19:15 UTC
Hello, I would like to set the position of the tooltip myself
![image](https://user-images.githubusercontent.com/20324066/224567453-b07c502b-5d98-48f2-a8d6-fd33560b49ab.png)

**Comment by ujas-m-simformsolutions** [comment] 2023-03-14 07:44
Duplicate of #312

**Closed by ujas-m-simformsolutions** 2023-03-14 07:44 UTC
Labels: duplicate
