### ISSUE TITLE
Analysis Issue after flutter upgrade to 3.22

### ISSUE THREAD

**Issue by enesakbal** [SimformSolutionsPvtLtd/flutter_showcaseview#440] opened 2024-05-16 07:12 UTC
I upgraded to flutter version 3.22.0 and I'm getting the following error.

```shell
Xcode build done.                                           25.1s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../.pub-cache/hosted/pub.dev/showcaseview-2.1.1/lib/src/tooltip_widget.dart:156:14: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
2

Error launching application on TEST IPHONE.
```

**Comment by aditya-css** [comment] 2024-05-16 08:06
Duplicate of #434

**Closed by aditya-css** 2024-05-16 08:06 UTC
