### ISSUE TITLE
Dont respond to any clicks in target

### ISSUE THREAD

**Issue by Tristannos** [SimformSolutionsPvtLtd/flutter_showcaseview#346] opened 2023-02-28 13:54 UTC
When i am showcasing things i don't want them to be able to click on the item in the target.

Make the target absorb the pointer when the current showcase is selected

**Comment by luccasclezar** [comment] 2023-02-28 19:16
Hey @Tristannos, if you want to test my fix you can use this in your pubspec:

```YAML
  showcaseview:
    git: https://github.com/luccasclezar/flutter_showcaseview.git
```

Or fork my repo and change the url to your fork.

**Comment by ujas-m-simformsolutions** [comment] 2023-03-01 06:38
@Tristannos you can do this by setting `disableDefaultTargetGestures` parameter to true.

```
Showcase(
  disableDefaultTargetGestures: true,
...
),
```

**Comment by ujas-m-simformsolutions** [comment] 2023-03-01 06:39
@luccasclezar your PR is related to overlay layout so it won't have any effect on gestures.

**Comment by luccasclezar** [comment] 2023-03-01 12:24
@ujas-m-simformsolutions The overlay that prevents gestures from passing through the barrier is misplaced. My PR fixes the overlay's position so that it can correctly intercept gestures. 🙂

**Comment by vatsaltanna** [comment] 2023-03-06 21:40
Hi @Tristannos , You can use below code to disable gestures on target widget.

```
disposeOnTap: false,
onTargetClick: () {},
```

**Comment by luis901101** [comment] 2023-03-06 21:49
> Hi @Tristannos , You can use below code to disable gestures on target widget.
> 
> ```
> disposeOnTap: false,
> onTargetClick: () {},
> ```
> 
> PS: Closing this issue for now, feel free to reopen this issue if this solutions doesn't work for you.

In my case I have a FAB as target widget and if I tap on it, then it's `onPressed` function get's called back.

**Comment by vatsaltanna** [comment] 2023-03-06 22:00
> > Hi @Tristannos , You can use below code to disable gestures on target widget.
> > ```
> > disposeOnTap: false,
> > onTargetClick: () {},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS: Closing this issue for now, feel free to reopen this issue if this solutions doesn't work for you.
> 
> In my case I have a FAB as target widget and if I tap on it, then it's `onPressed` function get's called back.

have you tried the configuration I have shared?

**Comment by vatsaltanna** [comment] 2023-03-06 22:02
Don't forget to remove `disableDefaultTargetGestures: true,` from the code only use below code.
```
disposeOnTap: false,
onTargetClick: () {},
```

**Comment by luis901101** [comment] 2023-03-06 22:13
Yep, since the first time, 

> Don't forget to remove `disableDefaultTargetGestures: true,` from the code only use below code.
> 
> ```
> disposeOnTap: false,
> onTargetClick: () {},
> ```

Yess, this was my initial configuration, I just checked each property an it's documentation and this one you propose is the right but it doesn't work as expected in my case. I have `ShowCaseWidget` as parent of Scaffold and `Showcase` as child of scafold's `floatingActionButton:` property.

**Comment by vatsaltanna** [comment] 2023-03-06 22:19
Yup that is fine, I tried with floating action button in example with the same config I shared with you and it works fine it ignores the omPressed event of FAB. Can you please share a reproducible code snippet of the issue you are facing ?

**Comment by luis901101** [comment] 2023-03-06 22:33
##  `flutter doctor -v`

```
[✓] Flutter (Channel stable, 3.7.4, on macOS 13.0 22A380 darwin-arm64, locale en-US)
    • Flutter version 3.7.4 on channel stable at /Users/user/fvm/versions/3.7.4
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b4bce91dd0 (2 weeks ago), 2023-02-21 09:50:50 +0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/user/Android/SDK
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/user/Android/SDK
    • Java binary at: /Users/user/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.
```

## Reproducible code snippet:

```dart
import 'package:flutter/material.dart';
import 'package:showcaseview/showcaseview.dart';

class TestShowcase extends StatefulWidget {
  static Future start(BuildContext context) => Navigator.push(
      context, MaterialPageRoute(builder: (context) => TestShowcase()));

  @override
  State createState() => _TestShowcaseState();
}

class _TestShowcaseState extends State<TestShowcase> {
  final fabKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return ShowCaseWidget(
      builder: Builder(
        builder: (context) {
          return Scaffold(
            floatingActionButton: Showcase(
              key: fabKey,
              disposeOnTap: false,
              onTargetClick: () {
                print('onTargetClick from Showcase');
              },
              targetShapeBorder: const CircleBorder(),
              targetPadding: const EdgeInsets.all(4),
              description: 'Fab onTargetClick test',
              child: FloatingActionButton(
                shape: const CircleBorder(),
                onPressed: () {
                  print('onPressed from FAB');
                },
              ),
            ),
            body: Center(
              child: ElevatedButton(
                child: const Text('Start ShowCase'),
                onPressed: () {
                  ShowCaseWidget.of(context).startShowCase([fabKey]);
                },
              ),
            ),
          );
        },
      ),
    );
  }
}
```

**Comment by vatsaltanna** [comment] 2023-03-07 06:23
This issue is reproduciable. @luis901101 Thanks for the code snippet. was this working as expected in previous flutter version ?

**Comment by luis901101** [comment] 2023-03-07 12:10
> This issue is reproduciable. @luis901101 Thanks for the code snippet. was this working as expected in previous flutter version ?

Not sure, I just started using it in a new project with this 3.7.4 flutter version

**Comment by dshpindler** [comment] 2023-03-09 18:21
I'm having the same issue since upgrading to flutter 3.7.x.
the pointer was absorbed properly before
(if you tap very close to the edge of the showcase child, you will get desired behavior)

**Comment by vatsaltanna** [comment] 2023-03-09 18:26
we will release the new version as soon as possible. meanwhile you can use the previoud version of showcaseview `showcaseview: ^2.0.0+1`.

**Comment by vatsaltanna** [comment] 2023-03-10 12:39
This issue has been fixed in latest release `showcaseview: ^2.0.2`. please use below code to avoid gestures on target widget.

```
disposeOnTap: false,
onTargetClick: () {},
```

**Closed by vatsaltanna** 2023-03-10 12:39 UTC

**Comment by AlmutawakelSukaina** [comment] 2023-03-11 07:47
@Tristannos does your issue resolved with new version showcaseview: ^2.0.2?!

**Comment by vatsaltanna** [comment] 2023-03-11 08:37
Hi @AlmutawakelSukaina , please remove flag `disableDefaultTargetGestures: true,` and add below code.
```
disposeOnTap: false,
onTargetClick: () {},
```

Note: `disableDefaultTargetGestures: true` allows external gesture to work so if you will remove it then default value will be false

**Comment by AlmutawakelSukaina** [comment] 2023-03-11 09:32
@vatsaltanna  Thank you that's work for me
